[NFC] Dockerfile + Bazel Fixes (#5)
Fixes a few issues:
1. Volume mounting `.cache/bazel` resulted in the parent `.cache`
directory to be root-owned, which caused issues with other tools run
inside the container under user privileges (e.g. precommit). We instead
mount the `.cache` directory now.
2. Tighten up sudo permissions that were previously relaxed I think to
mitigate 1.
3. Fix Dockerfile warning at line 2 (uppercase AS)
4. Update torch nightly hashes to fix AOT tests that failed with:
```
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.                                          
    torch==2.7.0.dev20250131+cpu from https://download.pytorch.org/whl/nightly/cpu/torch-2.7.0.dev20250131%2Bcpu-cp310-cp310-manylinux_2_28_x86_64.whl (from -r /tmp/tmps8m_o6as (line 1)):                                                                                    
        Expected sha256 022eb7ef864640b7b15e4a500dd1354bfc1658cc153e141daf7496d363966179                                                                                                                                                                                       
        Expected     or 1541bffc5543a9b10cd7b35aa9c425ccc46b628f73d4373bef79da6553fe68df                                                                                                                                                                                       
        Expected     or 175bf1384ff95f258728b5134c6caec3e6dbaadaa2c458430dd937464295545e                                                                                                                                                                                       
        Expected     or 2aea676c6ea0e8a8b7e72ceefe1668cd781a65a58690a9d0e7519a9f5425886e                                                                                                                                                                                       
        Expected     or 2b6ddf8dc1040c9ee25984d07ac752a68631b919222d778db94798c24e84d3ff                                                                                                                                                                                       
        Expected     or 2f51554094f2d6857ff52517fbb8186b6329a6cacf9fa1de1c0c983542f77678                                                                                                                                                                                       
        Expected     or 3030deb8a2466308f8ebb8b755503735b880442fde88ad93f216f5a866cae5fe                                                                                                                                                                                       
        Expected     or 3c5eeaff12c910d9c86b5ebe16f3614abab14744fc961e0c445fb906462f9377                                                                                                                                                                                       
        Expected     or 49c4c50e1557d6b507ea05d762bbf2744c1e9287852baa6d6b75de6c4c011da2                                                                                                                                                                                       
        Expected     or 596a4f0586ad121db78f92b602320a6b581ebde99dd53b056767923c90fc989a                                                                                                                                                                                       
        Expected     or 61a5012814824221b3f44552411c60f3b217e0077197288b29646c528abad073                                                                                                                                                                                       
        Expected     or 63fd0a0239f7147f05e840a679904577b7633cf0568494b23aebffca1bea2edf                                                                                                                                                                                       
        Expected     or 75a7d8692dd1ac09933fd66980d05c6f13754d19a2bdf9519ad7819b267971cd                                                                                                                                                                                       
        Expected     or 859e91760d7151bdf18caf7f2a9afc514c150bda9a4679b1261699dfff56a33d                                                                                                                                                                                       
        Expected     or 8e61f9d174ab180592190a011ea0261afdf53f1df85d3eaf7e72a555ea106044                                                                                                                                                                                       
        Expected     or 9f98be38a676681236ac8850b6cece04d53679e95e389952a57dd1fa089f8cb9                                                                                                                                                                                       
        Expected     or bb9bb80a25c1b4d55ff6e23a016493db31f3b66b43cd87277244cd250e979689                                                                                                                                                                                       
        Expected     or cb6ca0cdc88cdf80f35925844dcf0c0fd55dcd6d2a7f7a96c20fa47700b38e8b                                                                                                                                                                                       
        Expected     or d3c7633aad4005230783d4e8b87b143b3cef6fdaa2ff695354b4b1670c9b7656                                                                                                                                                                                       
        Expected     or d5ef26cd431a46792a4ea045995d2900ea2a36a4281d3b67e208ea9988c1caff                                                                                                                                                                                       
        Expected     or f0cf7ab37a4b4e1d38c1b9b2b5cd4a8ae03a46e14707ffc5ee88dfdd6ea9ac41                                                                                                                                                                                       
        Expected     or f5a9b35bd115f1009064fc36f5d9fff040f9ae096b9a35da09f5293d1b127fe0                                                                                                                                                                                       
             Got        c8ce5210a83cc8f2d516b1f489026b84a90e01998940ea13210926944596de5a                                                                                                                                                                                       
                                                                                      
```